name: manual-dispatch

on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: hello
        required: true
        description: a cheeful world

      log-level:
        type: choice
        options:
          - info
          - warn
          - error

jobs:
  run:
    runs-on: ubuntu:latest
    steps:
      - run: echo "${{ inputs.greeting }}"
