name: contexts

on: push

jobs:
  print:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      ACTOR: ${{ github.actor }}
    steps:
      - run: echo "${{ github.actor }}" # workflow executer be printed
      - run: echo "${ACTOR}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
